#!/bin/bash
set -e

cd $(dirname $0)

if [ ! -f ../internal/ui/ui/dashboard/index.html ]; then
  ./download
else
  echo "Using dashboard UI assets from the repository"
fi
./validate
./build
if [ -z "${SKIP_PACKAGE}" ]; then
  ./package
fi
